name: chatwhiz
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  get:
  get_storage:
  fluent_ui:
  dynamic_color:
  bitsdojo_window:
  url_launcher:
  device_info_plus:
  dio:
  flutter_colorpicker: 
  flutter_markdown: 
  flutter_i18n: 
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

