name: Build ChatWhiz

on:
  push:
    branches: ["main"]
    paths:
      - "**/*"
      - "!README.md"
      - "!README_CN.md"
      - "public/**"
  pull_request:
    branches: ["main"]
    paths:
      - "**/*"
      - "!README.md"
      - "!README_CN.md"
      - "public/**"

jobs:
  build_android:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.0"
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ChatWhiz-Android
          path: build/app/outputs/flutter-apk/*.apk

  build_ios:
    name: Build IPA (No Code Signing)
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.0"
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS (No Code Signing)
        run: |
          flutter build ios --release --no-codesign
          ln -sf ./build/ios/iphoneos Payload
          rm -rf build/ios/iphoneos/Runner.app/Frameworks/libswift*.dylib
          ls -lh build/ios/iphoneos/Runner.app/Frameworks/
          zip -r9 app.ipa Payload/runner.app

      - name: Rename IPA
        run: |
          version_name=$(yq e .version pubspec.yaml | cut -d "+" -f 1)
          for file in app.ipa; do
            new_file_name="build/ChatWhiz-${version_name}.ipa"
            mv "$file" "$new_file_name"
          done

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ChatWhiz-iOS
          path: build/ChatWhiz-*.ipa

  build_linux:
    name: Build Linux Executable
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.0"
          channel: stable

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev
          flutter pub get

      - name: Build Linux
        run: flutter build linux

      - name: Upload Linux Binary
        uses: actions/upload-artifact@v4
        with:
          name: ChatWhiz-Linux
          path: build/linux/x64/release/bundle/*

  build_windows:
    name: Build Windows Executable
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.0"
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows

      - name: Upload Windows Binary
        uses: actions/upload-artifact@v4
        with:
          name: ChatWhiz-Windows
          path: build/windows/x64/runner/Release/*